services:
  - type: web
    name: drawio-to-pptx
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.3"
